kafka:
  brokers:
    - kafka:9092
  version: 4.0.0
  assignor: roundrobin
  oldest: false
  verbose: true
runner:
  heartbeat_interval: 3
  frame_interval_millis: 3000
  orchestrator_grpc_addr: orchestrator:9090
  heartbeat_tries: 5